### ISSUE TITLE
broken pdf references

### ISSUE THREAD

**Issue by kabouzeid** [MarkHershey/arxiv-dl#10]
Links to references don't work when downloaded via arxiv-dl. I suspect the `add_pdf_metadata` function is destroying this somehow.

https://github.com/MarkHershey/arxiv-dl/blob/aa58b68cd8dbb47335b3f173d202342cbb9f02e4/arxiv_dl/helpers.py#L129

**Comment by kabouzeid** [comment]
just tested it, uncommenting this line fixes references

**Comment by MarkHershey** [comment]
This issue is fixed in 698819fba984d1d6224069536a87dc62ef2e9f01 and released in [v1.1.16](https://pypi.org/project/arxiv-dl/1.1.6/). Thanks @kabouzeid !
