### ISSUE TITLE
bulk download

### ISSUE THREAD

**Issue by flckv** [MarkHershey/arxiv-dl#8]
great work. Did you try downloading all arxiv papers in a specific category e.g.: biology to local folder?

**Comment by MarkHershey** [comment]
I recommend that you could

1. Use the [official arXiv API](https://info.arxiv.org/help/api/user-manual.html#query_details) to query papers from a specific category. Alternatively, use the [Python wrapper](https://github.com/lukasschwab/arxiv.py) for the arXiv API.
2. Save the queried paper (their URL or id) into a `.txt` file
3. Follow the instruction here #6
