### ISSUE TITLE
000_Paper_List.json

### ISSUE THREAD

**Issue by kabouzeid** [MarkHershey/arxiv-dl#9]
Thank you for open-sourcing this tool! I've been using it for a few weeks now and am very happy with it. Could you explain the purpose of the `000_Paper_List.json` file?

**Comment by MarkHershey** [comment]
It serves as a cache for `arxiv-dl`, preventing repeated downloads of the same papers. It also allows for quick local searches by keyword—either within the `000_Paper_List.json` file using `Ctrl+F`, or via Spotlight Search if you're on a Mac.

**Comment by kabouzeid** [comment]
Thanks for the explanation! I believe Spotlight already searches through PDF contents. And for deduplication, it’s probably better to check against the actual list of files since they already contain the arXiv ID in their names. The JSON file can get out of sync, for example, if a file is manually deleted.

**Comment by MarkHershey** [comment]
Well, it includes metadata such as comments (conference acceptance info), code URLs, and BibTeX entries that don't appear in the PDF. I believe that performing a text-based search within the file is faster and more reliable than using Spotlight to scan PDFs, which may have tokenization issues. Plus, Linux and Windows users don't have Spotlight. Overall, I'm just offering a flexible, hacky option—users can determine the use case based on their needs.
